#!/bin/sh /etc/rc.common

# https://openwrt.org/docs/guide-developer/procd-init-scripts#service_parameters

USE_PROCD=1

EXECUTABLE=/usr/sbin/plug2proxy
CONFIG=/etc/plug2proxy/config.json
DATA_DIR=/etc/plug2proxy

start_service() {
    procd_open_instance [plug2proxy]
    procd_set_param env RUST_LOG=plug2proxy=debug
    procd_set_param command $EXECUTABLE $CONFIG --data-dir $DATA_DIR
    procd_set_param file $CONFIG
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
