[package]
name = "plug2proxy-new"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
flume = "0.12.0"
futures = "0.3.31"
lits = "0.3.1"
log = "0.4.29"
lowkit.path = "../lowkit"
postcard = "1.1.3"
serde = "1.0.228"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
tokio-quiche = "0.13.0"
uuid = { version = "1.19.0", features = ["serde", "v4"] }

[lints.clippy]
collapsible_else_if = "allow"
collapsible_if = "allow"
disallowed_macros = "warn"
module_inception = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[dev-dependencies]
test-log = "0.2.19"
