type: in
id: in-main
hub_addr: "127.0.0.1:8765"
hub_host: "localhost"
connection_count: 4

socks5:
  listen: "127.0.0.1:1080"
  # Optional authentication
  # auth:
  #   username: "user"
  #   password: "pass"
