use std::path::{Path, PathBuf};

use lits::duration;
use pem::PemError;
use rcgen::{
  BasicConstraints, CertificateParams, DnType, ExtendedKeyUsagePurpose, IsCa, Issuer, KeyPair,
  KeyUsagePurpose,
};
use tokio::io::AsyncWriteExt;

use crate::constants::{ORGANIZATION_NAME, SERVER_COMMON_NAME};

pub const CA_COMMON_NAME: &str = "Plug2Proxy CA";

pub const CA_PEM_FILE_NAME: &str = "ca.pem";
pub const NODE_PEM_FILE_NAME: &str = "node.pem";

pub async fn generate_ca_pem_file(dir: impl AsRef<Path>) -> Result<PathBuf, Error> {
  let dir = dir.as_ref();

  tokio::fs::create_dir_all(dir).await?;

  let mut params = CertificateParams::default();

  params
    .distinguished_name
    .push(DnType::CommonName, CA_COMMON_NAME);
  params
    .distinguished_name
    .push(DnType::OrganizationName, ORGANIZATION_NAME);

  let now = time::OffsetDateTime::now_utc();

  params.not_before = now;
  params.not_after = now + duration!("100 years");

  params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);

  params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];

  let key_pair = KeyPair::generate()?;

  let cert = params.self_signed(&key_pair)?;

  let pem_file_path = dir.join(CA_PEM_FILE_NAME);

  write_private_pem(
    &pem_file_path,
    [cert.pem(), key_pair.serialize_pem()].join("\n"),
  )
  .await?;

  Ok(pem_file_path)
}

pub async fn generate_node_pem_file(
  dir: impl AsRef<Path>,
  common_name: &str,
  in_subdir: bool,
) -> Result<PathBuf, Error> {
  let dir = dir.as_ref();

  let node_dir = if in_subdir {
    let subdir = dir.join(common_name);
    tokio::fs::create_dir_all(&subdir).await?;
    subdir
  } else {
    dir.to_owned()
  };

  let ca_pem = tokio::fs::read_to_string(dir.join(CA_PEM_FILE_NAME))
    .await
    .map_err(|error| {
      if error.kind() == std::io::ErrorKind::NotFound {
        Error::CaNotFound
      } else {
        error.into()
      }
    })?;

  let ca_pems = pem::parse_many(ca_pem)?;

  let ca_cert_pem = ca_pems
    .iter()
    .find(|p| p.tag() == "CERTIFICATE")
    .ok_or(Error::CaCertificateNotFound)?
    .to_string();

  let ca_key_pem = ca_pems
    .iter()
    .find(|p| p.tag() == "PRIVATE KEY")
    .ok_or(Error::CaPrivateKeyNotFound)?
    .to_string();

  let ca_key_pair = KeyPair::from_pem(&ca_key_pem)?;
  let issuer = Issuer::from_ca_cert_pem(&ca_cert_pem, ca_key_pair)?;

  let mut params = CertificateParams::default();

  params
    .distinguished_name
    .push(DnType::OrganizationName, ORGANIZATION_NAME);

  params
    .distinguished_name
    .push(DnType::CommonName, common_name);

  let now = time::OffsetDateTime::now_utc();

  params.not_before = now;
  params.not_after = now + duration!("100 years");

  params.is_ca = IsCa::NoCa;

  params.key_usages = vec![
    KeyUsagePurpose::DigitalSignature,
    KeyUsagePurpose::KeyEncipherment,
  ];

  params.extended_key_usages = vec![
    ExtendedKeyUsagePurpose::ServerAuth,
    ExtendedKeyUsagePurpose::ClientAuth,
  ];
  params.subject_alt_names = vec![rcgen::SanType::DnsName(SERVER_COMMON_NAME.try_into()?)];

  let node_key_pair = KeyPair::generate()?;

  let node_cert = params.signed_by(&node_key_pair, &issuer)?;

  let node_pem_file_path = node_dir.join(NODE_PEM_FILE_NAME);

  write_private_pem(
    &node_pem_file_path,
    [node_cert.pem(), node_key_pair.serialize_pem(), ca_cert_pem].join("\n"),
  )
  .await?;

  Ok(node_pem_file_path)
}

async fn write_private_pem(path: &Path, contents: String) -> Result<(), std::io::Error> {
  let mut options = tokio::fs::OpenOptions::new();
  options.create(true).truncate(true).write(true);

  #[cfg(unix)]
  {
    options.mode(0o600);
  }

  let mut file = options.open(path).await?;

  // mode() only affects newly created files, so also repair permissions when
  // replacing a PEM generated by an older version.
  #[cfg(unix)]
  {
    use std::os::unix::fs::PermissionsExt;
    file
      .set_permissions(std::fs::Permissions::from_mode(0o600))
      .await?;
  }

  file.write_all(contents.as_bytes()).await?;
  file.flush().await?;

  Ok(())
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
  #[error("I/O error: {0}")]
  Io(#[from] std::io::Error),
  #[error("PEM error: {0}")]
  Pem(#[from] PemError),
  #[error("RcGen error: {0}")]
  RcGen(#[from] rcgen::Error),
  #[error("CA PEM file not found")]
  CaNotFound,
  #[error("CERTIFICATE not found in CA PEM file")]
  CaCertificateNotFound,
  #[error("PRIVATE KEY not found in CA PEM file")]
  CaPrivateKeyNotFound,
}

#[cfg(all(test, unix))]
mod tests {
  use std::os::unix::fs::PermissionsExt;

  use super::*;
  use crate::test::test_dir;

  #[tokio::test]
  async fn generated_private_pems_are_owner_only() {
    let dir = test_dir().join(format!("cert_permissions_{}", uuid::Uuid::new_v4()));

    let ca_path = generate_ca_pem_file(&dir).await.unwrap();
    let node_path = generate_node_pem_file(&dir, "node", true).await.unwrap();

    assert_eq!(
      tokio::fs::metadata(ca_path)
        .await
        .unwrap()
        .permissions()
        .mode()
        & 0o777,
      0o600
    );
    assert_eq!(
      tokio::fs::metadata(node_path)
        .await
        .unwrap()
        .permissions()
        .mode()
        & 0o777,
      0o600
    );
  }
}
