use serde::{Deserialize, Serialize};

use crate::route::{Label, RuleConfig};

/// Node role identifier sent during registration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NodeRole {
    In,
    Out,
}

// Note: RuleConfig import is kept for HubMessage::RouteConfig

/// A routing decision with label and optional tag.
/// - Label: determines which node to route to (first-level routing)
/// - Tag: passed to OUT for second-level routing decisions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouteEntry {
    /// The routing label (e.g., DIRECT, PROXY, or custom OUT tag).
    pub label: Label,
    /// Optional tag for second-level routing at OUT.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

/// Request sent on a data stream.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ForwardRequest {
    /// TCP stream forwarding to a target.
    Tcp(TcpForwardRequest),
    /// UDP forwarding (full-cone NAT).
    Udp(UdpForwardRequest),
}

/// TCP forwarding request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TcpForwardRequest {
    /// Target hostname with port (e.g., "example.com:443").
    /// Used for TLS SNI, logging, and routing decisions.
    pub host: String,
    /// Resolved address (e.g., "1.2.3.4:443").
    /// If provided, used for actual connection instead of resolving hostname.
    /// Useful for direct IN→OUT tunnels where IN has already resolved the address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Routing entries (label + tag pairs, determined by IN via router).
    #[serde(default)]
    pub routes: Vec<RouteEntry>,
}

/// UDP forwarding request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UdpForwardRequest {
    /// Routing entries (label + tag pairs, determined by IN via router).
    #[serde(default)]
    pub routes: Vec<RouteEntry>,
}

/// Messages from node to HUB.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum NodeMessage {
    /// Register this node with HUB.
    /// The node's unique ID (UUID) is generated by the HUB.
    /// The node's name is extracted from its TLS certificate's Common Name.
    Register {
        role: NodeRole,
        /// Tags this node provides (for OUT) or empty (for IN).
        tags: Vec<String>,
    },
}

/// Messages from HUB to node.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum HubMessage {
    /// Registration acknowledged.
    Registered,
    /// Routing configuration (sent to IN).
    RouteConfig { rules: Vec<RuleConfig> },
    /// OUT node availability update (sent to IN).
    OutUpdate { outs: Vec<OutInfo> },
}

/// Information about an OUT node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutInfo {
    /// Unique identifier (UUID generated by HUB).
    pub id: String,
    /// Human-readable name (from TLS certificate Common Name).
    pub name: Option<String>,
    pub tags: Vec<String>,
    /// Connection info for direct connection (if applicable).
    pub direct_addr: Option<String>,
}
