use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

use super::*;
use crate::cert::{generate_ca, generate_node_cert};
use crate::node::RouteEntry;
use crate::route::{DomainRuleConfig, Label, OneOrMany, RuleConfig};

const TEST_CERT_PATH: &str = "test.pem";

/// Ensure test certificate exists in cwd.
fn ensure_test_cert() {
    use std::sync::Once;
    static INIT: Once = Once::new();

    INIT.call_once(|| {
        if !std::path::Path::new(TEST_CERT_PATH).exists() {
            let ca = generate_ca("test-ca").unwrap();
            let server_cert =
                generate_node_cert("test-server", &ca.cert_pem, &ca.key_pem, true).unwrap();
            server_cert.write_to_file(TEST_CERT_PATH).unwrap();
        }
    });
}

/// Test helper: create a ClientConfig with no certificates (disabled mTLS for tests).
fn test_client_config() -> ClientConfig {
    ClientConfig {
        pem_path: None,
        ca_pem_path: None,
    }
}

#[tokio::test]
async fn test_in_out_connect_to_hub() {
    let _ = tracing_subscriber::fmt::try_init();
    ensure_test_cert();

    // Start HUB
    let hub = Arc::new(Hub::new(HubConfig {
        pem_path: TEST_CERT_PATH.to_string(),
        ca_pem_path: None,
        tags: vec![],
    }));

    let hub_addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
    let listener = tokio::net::TcpListener::bind(hub_addr).await.unwrap();
    let hub_addr = listener.local_addr().unwrap();
    drop(listener);

    let hub_clone = Arc::clone(&hub);
    let hub_handle = tokio::spawn(async move {
        hub_clone.serve(hub_addr).await.unwrap();
    });

    // Give HUB time to start
    tokio::time::sleep(Duration::from_millis(100)).await;

    // Connect OUT first (so IN receives it in the initial update)
    let mut out = OutNode::new(vec!["direct".to_string()], vec![], test_client_config());
    out.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("OUT connected");

    // Give HUB time to process OUT registration
    tokio::time::sleep(Duration::from_millis(100)).await;

    // Connect IN
    let mut in_node = InNode::new(test_client_config());
    in_node.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("IN connected");

    // Verify IN received OUT info
    let outs = in_node.get_outs().await;
    assert_eq!(outs.len(), 1);
    // ID is now a UUID generated by HUB, just check it's not empty
    assert!(!outs[0].id.is_empty());
    assert_eq!(outs[0].tags, vec!["direct"]);

    hub_handle.abort();
}

#[tokio::test]
async fn test_full_proxy_flow() {
    let _ = tracing_subscriber::fmt::try_init();
    ensure_test_cert();

    // Start a simple echo server as the target
    let echo_listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let echo_addr = echo_listener.local_addr().unwrap();

    let echo_handle = tokio::spawn(async move {
        loop {
            let (mut stream, _) = echo_listener.accept().await.unwrap();
            tokio::spawn(async move {
                let mut buf = [0u8; 1024];
                loop {
                    let n = stream.read(&mut buf).await.unwrap();
                    if n == 0 {
                        break;
                    }
                    stream.write_all(&buf[..n]).await.unwrap();
                }
            });
        }
    });

    // Start HUB
    let hub = Arc::new(Hub::new(HubConfig {
        pem_path: TEST_CERT_PATH.to_string(),
        ca_pem_path: None,
        tags: vec![],
    }));

    let hub_addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
    let listener = TcpListener::bind(hub_addr).await.unwrap();
    let hub_addr = listener.local_addr().unwrap();
    drop(listener);

    let hub_clone = Arc::clone(&hub);
    let hub_handle = tokio::spawn(async move {
        hub_clone.serve(hub_addr).await.unwrap();
    });

    tokio::time::sleep(Duration::from_millis(100)).await;

    // Connect IN
    let mut in_node = InNode::new(test_client_config());
    in_node.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("IN connected to HUB");

    // Create proxied connection to echo server through HUB
    let stream = in_node.connect(&echo_addr.to_string()).await.unwrap();
    tracing::info!("proxied connection established");

    // Wait for relay to be set up on HUB side
    tokio::time::sleep(Duration::from_millis(200)).await;

    // Send data through the tunnel
    let test_data = b"Hello, proxy!";
    let n = stream.send(test_data).await.unwrap();
    tracing::info!("sent test data ({} bytes) on stream {}", n, stream.id());

    // Receive echoed data (with retry since QUIC stream recv is non-blocking)
    let mut buf = [0u8; 1024];
    let mut total_received = 0;
    for _ in 0..100 {
        let (n, fin) = stream.recv(&mut buf[total_received..]).await.unwrap();
        total_received += n;
        if total_received >= test_data.len() || fin {
            break;
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    tracing::info!("received {} bytes", total_received);

    assert_eq!(&buf[..total_received], test_data);
    tracing::info!("proxy flow test passed!");

    hub_handle.abort();
    echo_handle.abort();
}

#[tokio::test]
async fn test_multi_out_with_routing() {
    let _ = tracing_subscriber::fmt::try_init();
    ensure_test_cert();

    // Start three echo servers to represent different targets
    let echo1 = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let echo1_addr = echo1.local_addr().unwrap();
    let echo2 = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let echo2_addr = echo2.local_addr().unwrap();
    let echo3 = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let echo3_addr = echo3.local_addr().unwrap();

    // Spawn echo servers with identifiable responses
    let spawn_echo = |listener: TcpListener, prefix: &'static str| {
        tokio::spawn(async move {
            loop {
                let (mut stream, _) = listener.accept().await.unwrap();
                tokio::spawn(async move {
                    let mut buf = [0u8; 1024];
                    loop {
                        let n = stream.read(&mut buf).await.unwrap();
                        if n == 0 {
                            break;
                        }
                        // Echo with prefix to identify which server handled it
                        let response =
                            format!("[{}]{}", prefix, String::from_utf8_lossy(&buf[..n]));
                        stream.write_all(response.as_bytes()).await.unwrap();
                    }
                });
            }
        })
    };

    let echo1_handle = spawn_echo(echo1, "HUB");
    let echo2_handle = spawn_echo(echo2, "OUT1");
    let echo3_handle = spawn_echo(echo3, "OUT2");

    // Start HUB
    let hub = Arc::new(Hub::new(HubConfig {
        pem_path: TEST_CERT_PATH.to_string(),
        ca_pem_path: None,
        tags: vec![],
    }));

    let hub_addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
    let listener = TcpListener::bind(hub_addr).await.unwrap();
    let hub_addr = listener.local_addr().unwrap();
    drop(listener);

    // Set routing rules
    // - "example.com" -> "out1" tag
    // - "google.com" -> "out2" tag
    // - everything else -> no tag (handled by HUB)
    hub.set_route_rules(vec![
        RuleConfig::Domain(DomainRuleConfig {
            r#match: OneOrMany::One("example.com".to_string()),
            negate: false,
            out: OneOrMany::One(Label::Custom("out1".to_string())),
            priority: None,
            tag: None,
        }),
        RuleConfig::Domain(DomainRuleConfig {
            r#match: OneOrMany::One("google.com".to_string()),
            negate: false,
            out: OneOrMany::One(Label::Custom("out2".to_string())),
            priority: None,
            tag: None,
        }),
    ])
    .await;

    let hub_clone = Arc::clone(&hub);
    let hub_handle = tokio::spawn(async move {
        hub_clone.serve(hub_addr).await.unwrap();
    });

    tokio::time::sleep(Duration::from_millis(100)).await;

    // Connect OUT nodes with different tags
    let mut out1 = OutNode::new(vec!["out1".to_string()], vec![], test_client_config());
    out1.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("OUT1 connected with tag 'out1'");

    let mut out2 = OutNode::new(vec!["out2".to_string()], vec![], test_client_config());
    out2.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("OUT2 connected with tag 'out2'");

    // Spawn OUT run loops (though they won't actually handle traffic in this test
    // since HUB currently exits directly)
    tokio::spawn(async move {
        let _ = out1.run().await;
    });
    tokio::spawn(async move {
        let _ = out2.run().await;
    });

    tokio::time::sleep(Duration::from_millis(100)).await;

    // Connect IN
    let mut in_node = InNode::new(test_client_config());
    in_node.connect_hub(hub_addr, 1).await.unwrap();
    tracing::info!("IN connected to HUB");

    // Verify IN received both OUTs
    let outs = in_node.get_outs().await;
    assert_eq!(outs.len(), 2);
    tracing::info!("IN received {} OUT nodes", outs.len());

    // Test 1: Connect to echo1 (no matching rule, should go through HUB)
    tracing::info!("\n=== Test 1: No matching rule (HUB handles) ===");
    let stream1 = in_node.connect(&echo1_addr.to_string()).await.unwrap();
    tokio::time::sleep(Duration::from_millis(200)).await;

    let test_msg1 = b"test-hub";
    stream1.send(test_msg1).await.unwrap();

    let mut buf1 = vec![0u8; 1024];
    let mut received1 = 0;
    for _ in 0..50 {
        let (n, _) = stream1.recv(&mut buf1[received1..]).await.unwrap();
        received1 += n;
        if received1 > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(20)).await;
    }

    let response1 = String::from_utf8_lossy(&buf1[..received1]);
    tracing::info!("Response 1: {}", response1);
    assert!(response1.contains("[HUB]"));
    assert!(response1.contains("test-hub"));

    // Test 2: Connect through OUT1 - manually set tag to match 'out1'
    tracing::info!("\n=== Test 2: Force routing through OUT1 (simulating 'example.com' match) ===");
    // For testing, we'll manually create a connection with routes
    let connector2 = in_node.hub_connector().unwrap();
    let stream2 = connector2
        .connect_with_routes(
            &echo2_addr.to_string(),
            vec![RouteEntry {
                label: Label::Custom("out1".to_string()),
                tag: None,
            }],
        )
        .await
        .unwrap();
    tokio::time::sleep(Duration::from_millis(200)).await;

    let test_msg2 = b"test-out1";
    stream2.send(test_msg2).await.unwrap();

    let mut buf2 = vec![0u8; 1024];
    let mut received2 = 0;
    for _ in 0..50 {
        let (n, _) = stream2.recv(&mut buf2[received2..]).await.unwrap();
        received2 += n;
        if received2 > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(20)).await;
    }

    let response2 = String::from_utf8_lossy(&buf2[..received2]);
    tracing::info!("Response 2: {}", response2);
    // With OUT forwarding enabled, this should now show [OUT1]
    assert!(response2.contains("[OUT1]"), "Expected OUT1 routing");
    assert!(response2.contains("test-out1"));

    // Test 3: Connect through OUT2 - manually set tag to match 'out2'
    tracing::info!("\n=== Test 3: Force routing through OUT2 (simulating 'google.com' match) ===");
    // For testing, we'll manually create a connection with routes
    let connector3 = in_node.hub_connector().unwrap();
    let stream3 = connector3
        .connect_with_routes(
            &echo3_addr.to_string(),
            vec![RouteEntry {
                label: Label::Custom("out2".to_string()),
                tag: None,
            }],
        )
        .await
        .unwrap();
    tokio::time::sleep(Duration::from_millis(200)).await;

    let test_msg3 = b"test-out2";
    stream3.send(test_msg3).await.unwrap();

    let mut buf3 = vec![0u8; 1024];
    let mut received3 = 0;
    for _ in 0..50 {
        let (n, _) = stream3.recv(&mut buf3[received3..]).await.unwrap();
        received3 += n;
        if received3 > 0 {
            break;
        }
        tokio::time::sleep(Duration::from_millis(20)).await;
    }

    let response3 = String::from_utf8_lossy(&buf3[..received3]);
    tracing::info!("Response 3: {}", response3);
    // With OUT forwarding enabled, this should now show [OUT2]
    assert!(response3.contains("[OUT2]"), "Expected OUT2 routing");
    assert!(response3.contains("test-out2"));

    // Test 4: Verify route resolution works
    tracing::info!("\n=== Test 4: Verify route resolution ===");
    let routes_example = in_node.resolve_routes("example.com:80").await;
    let routes_google = in_node.resolve_routes("google.com:443").await;
    let routes_other = in_node.resolve_routes("other.com:80").await;
    tracing::info!("Routes for 'example.com:80': {:?}", routes_example);
    tracing::info!("Routes for 'google.com:443': {:?}", routes_google);
    tracing::info!("Routes for 'other.com:80': {:?}", routes_other);
    assert!(
        routes_example
            .iter()
            .any(|r| r.label == Label::Custom("out1".to_string()))
    );
    assert!(
        routes_google
            .iter()
            .any(|r| r.label == Label::Custom("out2".to_string()))
    );
    assert!(routes_other.is_empty());

    tracing::info!("\n✅ Multi-OUT routing test completed!");
    tracing::info!("✓ HUB direct exit (no routes): working");
    tracing::info!("✓ OUT1 forwarding (label 'out1'): working");
    tracing::info!("✓ OUT2 forwarding (label 'out2'): working");
    tracing::info!("✓ Route resolution: working");

    hub_handle.abort();
    echo1_handle.abort();
    echo2_handle.abort();
    echo3_handle.abort();
}
